### ISSUE TITLE
TODO for v1.0.0 (Late February 2024 Update)

### ISSUE THREAD

**Issue by mantasu** [mantasu/sunglasses-detector#2]
# Features and Improvements for v1.0.0

## Data
* [x] Update scripts to process dataset-by-dataset instead of task-by-task
* [x] Find or add more datasets for _classification_, _detection_, and _segmentation_
* [x] Write processing scripts, update `preprocess.py` CLI
* [x] Upload the datasets as a single big one to Kaggle

## Architecture
* [x] Add prediction interface to handle predictions and conversion + saving to different formats
* [x] Update base model to be extendable with glasses classifier, detector, and segmenter children
* [x] Change class-based model instantiation to arg-based, create default models for each specification
* [x] Require task for CLI, add size alias, detect device when `None`

## Features
* [x] Add detection dataset, tiny detection model, and binary detection wrapper
* [x] Identify the best hyperparameters and set them as default for each wrapper
* [x] Train models of different sizes and kinds for different tasks (36 in total)

## Documentation
* [x] Add a demo file and a collab notebook for quick examples
* [x] Crop only the eye area in the tables, add more example images to showcase features
* [x] Add the results for each model + their sizes, document training parameters
* [x] Document data download and preprocessing steps
* [x] Add type hints and documentation for the new classes/functions
* [x] Add dataset + model architecture references
